version: '3'

services:
  api-ms:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: catalog-api-ms
    ports:
      - "5000:5000"
    networks:
      - catalog_microservices_network
    depends_on:
      - database
  database:
    image: mysql:lts
    container_name: database_calatog
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: catalog
    ports:
      - "3306:3306"
    networks:
      - catalog_microservices_network



networks:
  catalog_microservices_network:
    driver: bridge
