name: Continuos Integration - Testing
on:
  pull_request:
  push:
    branches:
      - main
 
jobs:
  continuos-integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.X'
      
      - name: Install dependencies with poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      
      - name: Install libs for testing
        run: |
          poetry install

      - name: Run tests
        run: |
          poetry run pytest  
      